version: '3.3'

services:
  koa-server-redis:
    image: redis:7.0-rc3-alpine
    command: >
     --requirepass ${REDIS_PASSWORD}
    ports:
     - "6379:6379"

  koa-backend:
    build: ./
    depends_on:
     - koa-server-redis
    links:
     - koa-server-redis
    volumes:
     - ./src/:/usr/bin/koa-backend/src/
    ports:
     - "8888:8888"
    environment:
     - REDIS_HOST=koa-server-redis
     - REDIS_PORT=6379
    env_file:
     - .env
