version: '3.3'

services:
    node-app-redis:
        image: redis:7.0-rc3-alpine
        command: >
         --requirepass ${REDIS_PASSWORD}
        env_file:
         - .env
        ports:
         - "6379:6379"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5

    node-app:
        restart: on-failure
        build: ./node-app
        depends_on:
         - node-app-redis
        links:
         - node-app-redis
        volumes:
         - ./node-app/:/usr/bin/node-app
        ports:
         - "8080:8080"
        environment:
         - PORT=8080
         - REDIS_HOST=node-app-redis
         - REDIS_PORT=6379
        env_file:
         - .env

    nginx-web-proxy-server:
        build: ./frontend
        container_name: nginx-web-proxy-server
        ports:
         - "80:80"
        depends_on:
         - node-app
        networks:
         - app-net
        volumes:
         - ./frontend/html:/usr/share/nginx/html
        environment:
         - NGINX_HOST=localhost
         - NGINX_PORT=80

networks:
  app-net:
    external: true
